### ISSUE TITLE
Bulk upload student - The example email format error

### ISSUE THREAD

**Issue by JJJustCoding** [JJJustCoding/project-allocation-web#32]
Issue
The email format of the example excel file to upload students is wrong.
Now it is example1@email, should be change to example1@uni.sydney.edu.au.

![image](https://user-images.githubusercontent.com/22407219/120279662-496d4b00-c2e9-11eb-87c7-dfcf0da0fb26.png)

**Comment by Jessica-erbing** [comment]
Has been updated
